#name: Package
#
#on:
#  push:
#
#jobs:
#  build:
#    runs-on: ${{ matrix.os }}-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        include:
#          - os: ubuntu
#            target: x86_64-unknown-linux-gnu
#            bin: svci
#          - os: macos
#            target: x86_64-apple-darwin
#            bin: svci
#          - os: macos
#            target: aarch64-apple-darwin
#            bin: svci
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Setup Rust
#        uses: dtolnay/rust-toolchain@stable
#        with:
#          targets: ${{ matrix.target }}
#
#      - name: Setup Cache
#        uses: Swatinem/rust-cache@v2
#
#      - name: Install musl-tools on Linux
#        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
#        if: contains(matrix.os, 'ubuntu')
#
#      - name: Build for ${{ matrix.target }}
#        run: |
#          cargo build --locked --release --target ${{ matrix.target }}
#          cd target/${{ matrix.target }}/release
#          tar czvf ../../../${{ matrix }}
#
#  package:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Archive artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: release
#          path: target/${{ matrix.target }}/*
