name: Package

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu
            arch: amd64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu
            arch: arm64
            target: aarch64-unknown-linux-gnu
          - os: macos
            arch: amd64
            target: x86_64-apple-darwin
          - os: macos
            arch: arm64
            target: aarch64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Build for ${{ matrix.arch }}
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: target/${{ matrix.target }}/*
